# Generated by Django 5.0.6 on 2024-06-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0002_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
